Update init script

diff --git a/init-script/wondershaper b/init-script/wondershaper
--- a/init-script/wondershaper
+++ b/init-script/wondershaper
@@ -30,20 +30,19 @@ is_running() {
 case "$1" in
     start)
     if is_running; then
-        echo "Already started"
+        $0 stop
+    fi
+    echo "Starting $name"
+    cd "$dir"
+    if [ -z "$user" ]; then
+        sudo $cmd_start >> "$stdout_log" 2>> "$stderr_log" &
     else
-        echo "Starting $name"
-        cd "$dir"
-        if [ -z "$user" ]; then
-            sudo $cmd_start >> "$stdout_log" 2>> "$stderr_log" &
-        else
-            sudo -u "$user" $cmd_start >> "$stdout_log" 2>> "$stderr_log" &
-        fi
-        echo $! > "$pid_file"
-        if ! is_running; then
-            echo "Unable to start, see $stdout_log and $stderr_log"
-            exit 1
-        fi
+        sudo -u "$user" $cmd_start >> "$stdout_log" 2>> "$stderr_log" &
+    fi
+    echo $! > "$pid_file"
+    if ! is_running; then
+        echo "Unable to start, see $stdout_log and $stderr_log"
+        exit 1
     fi
     ;;
     stop)
